services:
  - type: web
    name: innovation-lab-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: innovationlab-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: innovationlab-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: innovationlab-db
          property: database
      - key: DATASOURCE_USER
        fromDatabase:
          name: innovationlab-db
          property: user
      - key: DATASOURCE_PASSWORD
        fromDatabase:
          name: innovationlab-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://innovation-lab-platform.netlify.app
      - key: COMPETITION_END
        value: 2026-08-15
      - key: GITHUB_CLIENT_ID
        value: Ov23liG6w3csuLdB25RE
      - key: GITHUB_CLIENT_SECRET
        sync: false
        value: ''

databases:
  - name: innovationlab-db
    databaseName: innovationlab
    plan: free
